run:
  # See the dedicated "run" documentation section.

output:
  format: colored-line-number


linters-settings:
  # See the dedicated "linters-settings" documentation section.

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - durationcheck
    - exportloopref
    - gocritic
    - godot
    - goimports
    - govet
    - misspell
    - prealloc
    - revive
    - unconvert
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  # See the dedicated "severity" documentation section.
