name: Build

on:
  push:
    branches: [ master, ci/add_github_ci ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x, tip]
        full-tests: [false]
        include:
          - go-version: 1.20.x
            full-tests: true

    runs-on: ubuntu-latest

    steps:
      - name: Setup go
        run: |
          curl -sL https://raw.githubusercontent.com/maxatome/install-go/v3.4/install-go.pl |
              perl - ${{ matrix.go-version }} $HOME/go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Linting
        if: matrix.full-tests
        run: |
          curl -sL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
              sh -s -- -b $HOME/go/bin v1.52.2
          $HOME/go/bin/golangci-lint run ./...

      - name: Testing
        continue-on-error: ${{ matrix.go-version == 'tip' }}
        run: |
          go version
          if [ ${{ matrix.full-tests }} = true ]; then
              GO_TEST_OPTS="-covermode=atomic -coverprofile=coverage.out"
          fi
          export GORACE="halt_on_error=1"
          go test -race $GO_TEST_OPTS ./...

      - name: Reporting
        if: matrix.full-tests
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@v0.0.11
          goveralls -coverprofile=coverage.out -service=github
